# Generated by Django 6.0.7 on 2026-07-29 14:05

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('rutina', 'Rutina de entrenamiento'), ('alimentacion', 'Plan de alimentación')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('pdf', models.FileField(blank=True, upload_to='plans/', verbose_name='PDF')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clients.clientprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
