# Generated by Django 6.0.7 on 2026-07-29 14:05

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('completo', 'Completo'), ('basico', 'Básico'), ('futbolista', 'Futbolista')], default='completo', max_length=20, verbose_name='Tipo de perfil')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de alta')),
                ('goal', models.TextField(blank=True, verbose_name='Objetivo')),
                ('internal_notes', models.TextField(blank=True, help_text='Solo visibles para el entrenador, nunca para el cliente.', verbose_name='Notas internas')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Posición')),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre del tutor')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del tutor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
