# Generated by Django 6.0.7 on 2026-07-29 14:05

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnduranceTestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Test')),
                ('unit', models.CharField(choices=[('segundos', 'Segundos'), ('repeticiones', 'Repeticiones'), ('metros', 'Metros')], default='segundos', max_length=20, verbose_name='Unidad')),
                ('lower_is_better', models.BooleanField(default=False, verbose_name='Menos es mejor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tipo de test',
                'verbose_name_plural': 'Tipos de test',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Ejercicio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso (kg)')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% grasa corporal')),
                ('muscle_mass_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% masa muscular')),
                ('water_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% agua')),
                ('visceral_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Grasa visceral')),
                ('basal_metabolism', models.PositiveIntegerField(blank=True, null=True, verbose_name='Metabolismo basal (kcal)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='clients.clientprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Medición corporal',
                'verbose_name_plural': 'Mediciones corporales',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnduranceTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('value', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endurance_tests', to='clients.clientprofile', verbose_name='Cliente')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='metrics.endurancetesttype', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test de resistencia',
                'verbose_name_plural': 'Tests de resistencia',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrengthPR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Peso (kg)')),
                ('reps', models.PositiveIntegerField(default=1, verbose_name='Repeticiones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_prs', to='clients.clientprofile', verbose_name='Cliente')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prs', to='metrics.exercise', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Récord de fuerza',
                'verbose_name_plural': 'Récords de fuerza',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
