# Generated by Django 6.0.7 on 2026-07-29 14:05

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bono_type', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo pequeño'), ('futbol', 'Fútbol')], default='individual', max_length=20, verbose_name='Tipo de bono')),
                ('sessions_total', models.PositiveIntegerField(default=10, verbose_name='Sesiones totales')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio')),
                ('purchase_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de compra')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='clients.clientprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo pequeño'), ('futbol', 'Fútbol')], default='individual', max_length=20, verbose_name='Tipo de sesión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del entrenador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada')),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bonos.bono', verbose_name='Bono')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-date'],
            },
        ),
    ]
